### ISSUE TITLE
DateFormatException in den DatePicker Tests wenn die Lokalisierung deutsch ist.

### ISSUE THREAD

**Issue by fhanspach** [iljabauer/agileselenium#42]
``` java
java.text.ParseException: Unparseable date: "20.07.16"
    at java.text.DateFormat.parse(DateFormat.java:357)
    at de.devboost.agileselenium.VaadinSeleniumSupport.getCurrentDate(VaadinSeleniumSupport.java:485)
    at de.devboost.agileselenium.VaadinSeleniumSupport.selectDateInDatePicker(VaadinSeleniumSupport.java:391)
    at de.devboost.agileselenium.SeleniumSupport.selectDateInDatePicker(SeleniumSupport.java:190)
    at de.devboost.agileselenium.test.datepicker.SelectInDatePickerAlreadyCorrectTest.executeScript(SelectInDatePickerAlreadyCorrectTest.java:63)
```

**Comment by fhanspach** [comment]
Das Datumsformat kann in `VaadinSeleniumSupport` spezifiziert werden. Was fehlt ist eine Möglichkeit es im Test zu ändern.
